"""修复ARRAY类型使用PostgreSQL方言

Revision ID: d53f4632bc0b
Revises: fcbe6d70e924
Create Date: 2025-03-01 19:18:48.927714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53f4632bc0b'
down_revision = 'fcbe6d70e924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 